### ISSUE TITLE
RuntimeError: DataLoader worker (pid 384930) is killed by signal: Segmentation fault.

### ISSUE THREAD

**Issue by darshitajain** [nicklashansen/dmcontrol-generalization-benchmark#19]
I ran your code of the SODA algorithm for 500k steps. The code ran till 211k steps and then it gave a segmentation fault error. 

Evaluating: logs/walker_walk/soda/0
| eval | S: 210000 | ER: 604.9552 | ERTEST: 473.9582
| train | E: 841 | S: 210250 | D: 77.9 s | R: 676.1391 | ALOSS: -200.7976 | CLOSS: 19.3476 | AUXLOSS: 0.0003
| train | E: 842 | S: 210500 | D: 21.4 s | R: 630.4664 | ALOSS: -200.9594 | CLOSS: 19.7981 | AUXLOSS: 0.0003
| train | E: 843 | S: 210750 | D: 21.5 s | R: 575.7474 | ALOSS: -201.1477 | CLOSS: 19.6175 | AUXLOSS: 0.0003
| train | E: 844 | S: 211000 | D: 21.5 s | R: 587.5916 | ALOSS: -201.0205 | CLOSS: 19.8251 | AUXLOSS: 0.0003
| train | E: 845 | S: 211250 | D: 21.7 s | R: 600.5652 | ALOSS: -200.9775 | CLOSS: 19.5227 | AUXLOSS: 0.0003
| train | E: 846 | S: 211500 | D: 21.5 s | R: 617.4011 | ALOSS: -201.0966 | CLOSS: 19.4789 | AUXLOSS: 0.0003
| train | E: 847 | S: 211750 | D: 21.5 s | R: 670.3287 | ALOSS: -200.8488 | CLOSS: 19.7286 | AUXLOSS: 0.0003
ERROR: Unexpected segmentation fault encountered in worker.
Traceback (most recent call last):
  File "src/train.py", line 152, in <module>
    main(args)
  File "src/train.py", line 136, in main
    agent.update(replay_buffer, L, step)
  File "/home/kumars/Darshita/dmcontrol-generalization-benchmark/src/algorithms/soda.py", line 75, in update
    self.update_critic(obs, action, reward, next_obs, not_done, L, step)
  File "/home/kumars/Darshita/dmcontrol-generalization-benchmark/src/algorithms/sac.py", line 93, in update_critic
    current_Q1, current_Q2 = self.critic(obs, action)
  File "/home/kumars/anaconda3/envs/crc/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/kumars/Darshita/dmcontrol-generalization-benchmark/src/algorithms/modules.py", line 248, in forward
    return self.Q1(x, action), self.Q2(x, action)
  File "/home/kumars/anaconda3/envs/crc/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/kumars/Darshita/dmcontrol-generalization-benchmark/src/algorithms/modules.py", line 232, in forward
    return self.trunk([torch.cat](http://torch.cat/)([obs, action], dim=1))
  File "/home/kumars/anaconda3/envs/crc/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/kumars/anaconda3/envs/crc/lib/python3.6/site-packages/torch/nn/modules/container.py", line 141, in forward
    input = module(input)
  File "/home/kumars/anaconda3/envs/crc/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/kumars/anaconda3/envs/crc/lib/python3.6/site-packages/torch/nn/modules/linear.py", line 103, in forward
    return F.linear(input, self.weight, self.bias)
  File "/home/kumars/anaconda3/envs/crc/lib/python3.6/site-packages/torch/nn/functional.py", line 1848, in linear
    return torch._C._nn.linear(input, weight, bias)
  File "/home/kumars/anaconda3/envs/crc/lib/python3.6/site-packages/torch/utils/data/_utils/signal_handling.py", line 66, in handler
    _error_if_any_worker_fails()
RuntimeError: DataLoader worker (pid 384930) is killed by signal: Segmentation fault.

@nicklashansen Can you please help in this regard?

**Comment by nicklashansen** [comment]
Thank you for reaching out. I have not encountered this problem before. Did you fix the issue? If not, can you provide a bit more context? Could this be due to OOM or I/O issues?

**Comment by swagatk** [comment]
Hi
Executed the code again. I want to confirm that the following code works fine:

```
$ python3 src/train.py --algorithm svea --seed 0
| train | E: 1991 | S: 497750 | D: 26.4 s | R: 753.6373 | ALOSS: -286.7129 | CLOSS: 7.1381 | AUXLOSS: 0.0000
| train | E: 1992 | S: 498000 | D: 26.4 s | R: 746.2775 | ALOSS: -286.7596 | CLOSS: 6.6472 | AUXLOSS: 0.0000
| train | E: 1993 | S: 498250 | D: 26.3 s | R: 698.4181 | ALOSS: -286.8658 | CLOSS: 6.7780 | AUXLOSS: 0.0000
| train | E: 1994 | S: 498500 | D: 26.4 s | R: 740.4771 | ALOSS: -286.8359 | CLOSS: 6.9838 | AUXLOSS: 0.0000
| train | E: 1995 | S: 498750 | D: 26.3 s | R: 765.1838 | ALOSS: -286.9472 | CLOSS: 6.7261 | AUXLOSS: 0.0000
| train | E: 1996 | S: 499000 | D: 26.4 s | R: 767.2537 | ALOSS: -286.8998 | CLOSS: 6.9302 | AUXLOSS: 0.0000
| train | E: 1997 | S: 499250 | D: 26.4 s | R: 777.9448 | ALOSS: -286.8531 | CLOSS: 6.9055 | AUXLOSS: 0.0000
| train | E: 1998 | S: 499500 | D: 26.5 s | R: 768.7053 | ALOSS: -286.8529 | CLOSS: 7.0283 | AUXLOSS: 0.0000
| train | E: 1999 | S: 499750 | D: 26.4 s | R: 748.4904 | ALOSS: -286.7525 | CLOSS: 7.3644 | AUXLOSS: 0.0000
| train | E: 2000 | S: 500000 | D: 26.5 s | R: 699.5410 | ALOSS: -286.9346 | CLOSS: 7.0425 | AUXLOSS: 0.0000
Evaluating: logs/walker_walk/svea/0
| eval | S: 500000 | ER: 739.2902 | ERTEST: 700.8506
Completed training for logs/walker_walk/svea/0
(crc) kumars@TH-Titan:~/Darshita/dmcontrol-generalization-benchmark$
---------------------------------------------------------------------------------
```

But I get error when I try to use 'soda' algorithm:

```
$ python3 ./src/train.py --algorithm soda --seed 0

| train | E: 27 | S: 6750 | D: 25.7 s | R: 91.7090 | ALOSS: -21.8489 | CLOSS: 4.6501 | AUXLOSS: 0.0017
| train | E: 28 | S: 7000 | D: 25.7 s | R: 176.0666 | ALOSS: -22.5547 | CLOSS: 4.4872 | AUXLOSS: 0.0017
| train | E: 29 | S: 7250 | D: 25.8 s | R: 160.3945 | ALOSS: -23.2271 | CLOSS: 4.3081 | AUXLOSS: 0.0017
| train | E: 30 | S: 7500 | D: 25.9 s | R: 148.7203 | ALOSS: -23.8829 | CLOSS: 4.5158 | AUXLOSS: 0.0017
| train | E: 31 | S: 7750 | D: 24.9 s | R: 170.4827 | ALOSS: -24.5775 | CLOSS: 4.5976 | AUXLOSS: 0.0016
| train | E: 32 | S: 8000 | D: 25.5 s | R: 158.0234 | ALOSS: -25.2575 | CLOSS: 4.6250 | AUXLOSS: 0.0016
| train | E: 33 | S: 8250 | D: 25.7 s | R: 196.4380 | ALOSS: -25.9858 | CLOSS: 4.9300 | AUXLOSS: 0.0016
| train | E: 34 | S: 8500 | D: 25.6 s | R: 193.5218 | ALOSS: -26.6831 | CLOSS: 4.6321 | AUXLOSS: 0.0016
| train | E: 35 | S: 8750 | D: 25.5 s | R: 193.2462 | ALOSS: -27.4102 | CLOSS: 4.6204 | AUXLOSS: 0.0015
Traceback (most recent call last):
  File "src/train.py", line 152, in <module>
    main(args)
  File "src/train.py", line 136, in main
    agent.update(replay_buffer, L, step)
  File "/home/kumars/Darshita/dmcontrol-generalization-benchmark/src/algorithms/soda.py", line 84, in update
    self.update_soda(replay_buffer, L, step)
  File "/home/kumars/Darshita/dmcontrol-generalization-benchmark/src/algorithms/soda.py", line 57, in update_soda
    aug_x = augmentations.random_overlay(aug_x)
  File "/home/kumars/Darshita/dmcontrol-generalization-benchmark/src/augmentations.py", line 61, in random_overlay
    imgs = _get_places_batch(batch_size=x.size(0)).repeat(1, x.size(1)//3, 1, 1)
  File "/home/kumars/Darshita/dmcontrol-generalization-benchmark/src/augmentations.py", line 43, in _get_places_batch
    imgs, _ = next(places_iter)
  File "/home/kumars/anaconda3/envs/crc/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/home/kumars/anaconda3/envs/crc/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 1183, in _next_data
    return self._process_data(data)
  File "/home/kumars/anaconda3/envs/crc/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 1229, in _process_data
    data.reraise()
  File "/home/kumars/anaconda3/envs/crc/lib/python3.6/site-packages/torch/_utils.py", line 434, in reraise
    raise exception
OSError: Caught OSError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/kumars/anaconda3/envs/crc/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/kumars/anaconda3/envs/crc/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/kumars/anaconda3/envs/crc/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/kumars/anaconda3/envs/crc/lib/python3.6/site-packages/torchvision/datasets/folder.py", line 138, in __getitem__
    sample = self.loader(path)
  File "/home/kumars/anaconda3/envs/crc/lib/python3.6/site-packages/torchvision/datasets/folder.py", line 174, in default_loader
    return pil_loader(path)
  File "/home/kumars/anaconda3/envs/crc/lib/python3.6/site-packages/torchvision/datasets/folder.py", line 157, in pil_loader
    return img.convert('RGB')
  File "/home/kumars/anaconda3/envs/crc/lib/python3.6/site-packages/PIL/Image.py", line 915, in convert
    self.load()
  File "/home/kumars/anaconda3/envs/crc/lib/python3.6/site-packages/PIL/ImageFile.py", line 274, in load
    raise_oserror(err_code)
  File "/home/kumars/anaconda3/envs/crc/lib/python3.6/site-packages/PIL/ImageFile.py", line 67, in raise_oserror
    raise OSError(message + " when reading image file")
OSError: broken data stream when reading image file

(crc) kumars@TH-Titan:~/Darshita/dmcontrol-generalization-benchmark$
------------------------
```
Is there anyway, I can run your soda algorithm? 
Thanks & Regards,
Swagat

**Comment by nicklashansen** [comment]
Based on your error message, the issue appears to be in loading images from disk. By default, SODA applies random overlay augmentation using the Places dataset, whereas SVEA uses random convolution augmentation. Can you confirm that you have downloaded this dataset as instructed in the README? Here: https://github.com/nicklashansen/dmcontrol-generalization-benchmark#datasets

The respective augmentations are applied here:
https://github.com/nicklashansen/dmcontrol-generalization-benchmark/blob/c8f8db78807bf8e47f64b3de535d4b57c1e36db7/src/algorithms/svea.py#L27
https://github.com/nicklashansen/dmcontrol-generalization-benchmark/blob/c8f8db78807bf8e47f64b3de535d4b57c1e36db7/src/algorithms/soda.py#L57

If you want to quickly try out SODA without downloading the dataset, you can switch out the default augmentation in favor of random convolution like in the SVEA implementation.

I'm closing the issue for now but feel free to reopen if you have follow-up questions.
