### ISSUE TITLE
TypeError: load() got an unexpected keyword argument 'setting_kwargs'

### ISSUE THREAD

**Issue by antoniopioricciardi** [nicklashansen/dmcontrol-generalization-benchmark#23]
Hi. I just made a fresh install following the instructions on the readme file.
When I run 
```
python3 src/train.py \
  --algorithm svea \
  --seed 0
```
I get
`AttributeError: 'dict' object has no attribute 'env_specs'`
This is easily solved by downgrading the python version from 0.26.0 to 0.19.0.

Now, instead, I get the following:

```
/home/antonioricciardi/anaconda3/envs/dmcgb_orig/lib/python3.7/site-packages/glfw/__init__.py:916: GLFWError: (65544) b'X11: The DISPLAY environment variable is missing'
  warnings.warn(message, GLFWError)
Traceback (most recent call last):
  File "src/train.py", line 150, in <module>
    main(args)
  File "src/train.py", line 50, in main
    mode='train'
  File "/home/antonioricciardi/projects/dmcontrol-generalization-benchmark/src/env/wrappers.py", line 48, in make_env
    background_dataset_paths=paths
  File "/home/antonioricciardi/projects/dmcontrol-generalization-benchmark/src/env/dmc2gym/dmc2gym/__init__.py", line 64, in make
    return gym.make(env_id)
  File "/home/antonioricciardi/anaconda3/envs/dmcgb_orig/lib/python3.7/site-packages/gym/envs/registration.py", line 145, in make
    return registry.make(id, **kwargs)
  File "/home/antonioricciardi/anaconda3/envs/dmcgb_orig/lib/python3.7/site-packages/gym/envs/registration.py", line 90, in make
    env = spec.make(**kwargs)
  File "/home/antonioricciardi/anaconda3/envs/dmcgb_orig/lib/python3.7/site-packages/gym/envs/registration.py", line 60, in make
    env = cls(**_kwargs)
  File "/home/antonioricciardi/projects/dmcontrol-generalization-benchmark/src/env/dmc2gym/dmc2gym/wrappers.py", line 90, in __init__
    setting_kwargs=setting_kwargs
TypeError: load() got an unexpected keyword argument 'setting_kwargs'
```

Have any ideas of how I can solve this? Thank you!

**Comment by antoniopioricciardi** [comment]
Ok, it seems like I managed to solve this.
I think the issue was that I already had another version of Mujoco in the $HOME/.mujoco/ folder (therefore I didn't receive any errors in this regard).

All I had to do was to download mujoco 200 from [here](https://www.roboti.us/download.html) and the activation key from [here](https://www.roboti.us/license.html), and past it in the .mujoco folder, although in the website says to put it inside .mujoco200_{os}/bin/ folder.

Moreover, the version of gym that gets installed by the dependencies is the 0.26.2, which, when running the code throws the  following error:
`AttributeError: 'dict' object has no attribute 'env_specs'`

The fix for this is to install an older gym version:
First run 

`pip uninstall gym
`
and then run

`pip install gym==0.19.0`

**Comment by DMU-XMU** [comment]
Hi, I also encountered this problem. Have you handled it successfully?

**Comment by Bxliang868** [comment]
Hi, I also encountered this problem. Have you handled it successfully?

**Comment by Bxliang868** [comment]
Traceback (most recent call last):
  File "src/train.py", line 150, in <module>
    main(args)
  File "src/train.py", line 50, in main
    mode='train'
  File "/mnt/Data_1/gaokai/lbx/GE/src/env/wrappers.py", line 48, in make_env
    background_dataset_paths=paths
  File "/mnt/Data_1/gaokai/lbx/SG/DMC/src/env/dmc2gym/dmc2gym/__init__.py", line 64, in make
    return gym.make(env_id)
  File "/mnt/Data_1/gaokai/miniconda3/envs/dmcgb/lib/python3.7/site-packages/gym/envs/registration.py", line 184, in make
    return registry.make(id, **kwargs)
  File "/mnt/Data_1/gaokai/miniconda3/envs/dmcgb/lib/python3.7/site-packages/gym/envs/registration.py", line 106, in make
    env = spec.make(**kwargs)
  File "/mnt/Data_1/gaokai/miniconda3/envs/dmcgb/lib/python3.7/site-packages/gym/envs/registration.py", line 76, in make
    env = cls(**_kwargs)
  File "/mnt/Data_1/gaokai/lbx/SG/DMC/src/env/dmc2gym/dmc2gym/wrappers.py", line 90, in __init__
    setting_kwargs=setting_kwargs
TypeError: load() got an unexpected keyword argument 'setting_kwargs'

I have installed mujoco 200 and gym==0.19.0.

**Comment by nicklashansen** [comment]
Hi @antoniopioricciardi @DMU-XMU @007lbx, did you install dependencies as described in the readme?

```
conda env create -f setup/conda.yaml
conda activate dmcgb
sh setup/install_envs.sh
```

Our benchmark requires our own packaged version of DMControl (and dmc2gym) in order to generate the randomized visuals; the `install_envs.sh` bash script should install those for you. I believe that the error `TypeError: load() got an unexpected keyword argument 'setting_kwargs'` stems from having the conda/pip distributed versions of DMControl installed on your system rather than our provided version.

**Comment by Bxliang868** [comment]
Thank you @nicklashansen  , it seems like I managed to solve this.

**Comment by nicklashansen** [comment]
@007lbx Sounds great! I will close this issue then, but feel free to re-open or create a new issue if you have any follow-up questions.
